"""empty message

Revision ID: 0152da0b9c45
Revises: 2547d822e98f
Create Date: 2021-05-14 20:49:42.335641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0152da0b9c45'
down_revision = '2547d822e98f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favoriteWord', 'translated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favoriteWord', sa.Column('translated', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
