"""empty message

Revision ID: 2547d822e98f
Revises: 
Create Date: 2021-05-14 20:01:00.693575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2547d822e98f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('firstname', sa.String(length=120), nullable=False),
    sa.Column('lastname', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('is_Active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('favoriteWord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=120), nullable=False),
    sa.Column('translated', sa.String(length=120), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favoriteWord')
    op.drop_table('user')
    # ### end Alembic commands ###
