"""empty message

Revision ID: ea41a77514ed
Revises: 314d9f3e5629
Create Date: 2021-04-20 03:10:22.194148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea41a77514ed'
down_revision = '314d9f3e5629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('url', sa.String(length=280), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'url')
    # ### end Alembic commands ###
